### ISSUE TITLE
Add new metrics captures to SiteImprove (meta) (from 1869)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/test1-lux-frontend#52]
**Problem Description:**
In discussions of #1729 and autocomplete, we realized that there are additional events that Site Improve could capture. This ticket has been expanded to cover all improvements to SiteImprove tracking. 

**Expected Behavior/Solution:**
Improve the ability to get meaningful data from SiteImprove with additional events and other analytics tracking and reports. 

**Requirements:**
 https://docs.google.com/spreadsheets/d/1VICQvsPW2IJpkOFV20dGoIe5DsiLp-geYW_d3nXtcZk/edit#gid=0

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.
- [x] Consultation with SI - Peter, Jeff, Sarah
- [x] Documentation of Requirements - team
- [x] Decision needed: manage implementation here (meta ticket) or on spreadsheet (above)? - Peter, Amy
       - Implementation will be done in the spreadsheet. 
- [x] Review spreadsheet and make sure it is accurate - Amy, Peter, Mike, others as needed
- [ ] https://git.yale.edu/lux-its/lux-web/issues/2044 
- [ ] https://git.yale.edu/lux-its/lux-web/issues/2046
- [ ] https://git.yale.edu/lux-its/lux-web/issues/2015 - Peter
- [ ] https://git.yale.edu/lux-its/lux-web/issues/2016 - Peter - nice to have, but not required
- [x] https://git.yale.edu/lux-its/lux-web/issues/1994
- [ ] Track implementation on spreadsheet for each requirement - Amy

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**
- https://git.yale.edu/lux-its/lux-web/issues/2016 
- https://git.yale.edu/lux-its/lux-web/issues/2015
NOTE: work can proceed without this, but there will be some code updates when this gets deployed

**Related Github Issues:**

**Related links:**
- [Teams Chat](https://teams.microsoft.com/l/message/19:GmLeQu1cBR40mfrno-l8lngg7RFCcJs8fvFIw-MJjIM1@thread.tacv2/1695222335858?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1695222335858&teamName=MarkLogic&channelName=General&createdTime=1695222335858&allowXTenantAccess=false)

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.
